import type {WorkstationProject} from "./schema";

const rise = {
  entrance: "rise" as const,
  exit: "fade" as const,
  intensity: 0.65,
};

const fade = {
  entrance: "fade" as const,
  exit: "fade" as const,
  intensity: 0.4,
};

export const workstationDemoProject: WorkstationProject = {
  schemaVersion: 1,
  name: "ERP Explainer Starter",
  fps: 30,
  width: 1920,
  height: 1080,
  durationInFrames: 360,
  background: "#0B1020",
  tracks: [
    {
      id: "background",
      name: "Background",
      visible: true,
      locked: true,
      items: [
        {
          id: "panel",
          name: "Main panel",
          type: "solid",
          timing: {from: 0, durationInFrames: 360},
          transform: {x: 70, y: 60, width: 1780, height: 960, rotation: 0, opacity: 1, scale: 1},
          motion: {entrance: "none", exit: "none", intensity: 0},
          color: "#121A2E",
          radius: 42,
        },
      ],
    },
    {
      id: "titles",
      name: "Titles",
      visible: true,
      locked: false,
      items: [
        {
          id: "eyebrow",
          name: "Eyebrow",
          type: "text",
          timing: {from: 8, durationInFrames: 270},
          transform: {x: 140, y: 122, width: 650, height: 58, rotation: 0, opacity: 1, scale: 1},
          motion: rise,
          text: "VMT • ERP EXPLAINER WORKSTATION",
          style: {
            color: "#55E6C1",
            fontFamily: "Arial",
            fontSize: 28,
            fontWeight: 700,
            textAlign: "left",
            lineHeight: 1.1,
          },
        },
        {
          id: "headline",
          name: "Headline",
          type: "text",
          timing: {from: 14, durationInFrames: 265},
          transform: {x: 140, y: 188, width: 720, height: 200, rotation: 0, opacity: 1, scale: 1},
          motion: rise,
          text: "Show the workflow.\nNot just the software.",
          style: {
            color: "#FFFFFF",
            fontFamily: "Arial",
            fontSize: 72,
            fontWeight: 700,
            textAlign: "left",
            lineHeight: 1.03,
          },
        },
        {
          id: "body",
          name: "Body copy",
          type: "text",
          timing: {from: 24, durationInFrames: 250},
          transform: {x: 144, y: 430, width: 690, height: 130, rotation: 0, opacity: 1, scale: 1},
          motion: fade,
          text: "Use screenshots, cursor movement, annotations and process flows to explain any VMT ERP or digital platform.",
          style: {
            color: "#C7D1E5",
            fontFamily: "Arial",
            fontSize: 31,
            fontWeight: 400,
            textAlign: "left",
            lineHeight: 1.36,
          },
        },
      ],
    },
    {
      id: "application",
      name: "Application Demo",
      visible: true,
      locked: false,
      items: [
        {
          id: "browser",
          name: "ERP browser window",
          type: "browser-window",
          timing: {from: 28, durationInFrames: 268},
          transform: {x: 900, y: 120, width: 820, height: 610, rotation: -1.25, opacity: 1, scale: 1},
          motion: {entrance: "scale", exit: "fade", intensity: 0.65},
          title: "ERP",
          url: "erp.example.local/dashboard",
          accent: "#55E6C1",
          chrome: "dark",
        },
        {
          id: "cursor",
          name: "Cursor click",
          type: "cursor",
          timing: {from: 72, durationInFrames: 120},
          transform: {x: 1110, y: 300, width: 72, height: 72, rotation: 0, opacity: 1, scale: 1},
          animation: {
            x: [
              {frame: 0, value: 1110, easing: "ease-in-out"},
              {frame: 30, value: 1286, easing: "ease-in-out"},
              {frame: 72, value: 1470, easing: "ease-in-out"},
            ],
            y: [
              {frame: 0, value: 300, easing: "ease-in-out"},
              {frame: 30, value: 366, easing: "ease-in-out"},
              {frame: 72, value: 510, easing: "ease-in-out"},
            ],
            scale: [
              {frame: 0, value: 1, easing: "linear"},
              {frame: 34, value: 1, easing: "linear"},
              {frame: 38, value: 0.9, easing: "ease-out"},
              {frame: 44, value: 1, easing: "ease-out"},
            ],
          },
          motion: {entrance: "fade", exit: "fade", intensity: 0.4},
          variant: "pointer",
          color: "#FFFFFF",
          clickAtFrame: 34,
        },
        {
          id: "callout",
          name: "Feature callout",
          type: "callout",
          timing: {from: 102, durationInFrames: 118},
          transform: {x: 1115, y: 625, width: 490, height: 112, rotation: 0, opacity: 1, scale: 1},
          motion: rise,
          label: "Open the beneficiary workspace",
          accent: "#55E6C1",
          foreground: "#0F172A",
          background: "#FFFFFF",
          direction: "up",
        },
      ],
    },
    {
      id: "workflow",
      name: "Workflow",
      visible: true,
      locked: false,
      items: [
        {
          id: "process-flow",
          name: "ERP workflow",
          type: "flow",
          timing: {from: 194, durationInFrames: 138},
          transform: {x: 140, y: 785, width: 1580, height: 120, rotation: 0, opacity: 1, scale: 1},
          motion: rise,
          steps: ["Beneficiary", "Programme", "Activity", "Evidence", "Report"],
          accent: "#55E6C1",
          foreground: "#0F172A",
          surface: "#FFFFFF",
        },
      ],
    },
  ],
};
