import type {WorkstationProject} from "./schema";

export const workstationDemoProject: WorkstationProject = {
  schemaVersion: 1,
  name: "ERP Explainer Starter",
  fps: 30,
  width: 1920,
  height: 1080,
  durationInFrames: 300,
  background: "#0B1020",
  tracks: [
    {
      id: "background",
      name: "Background",
      visible: true,
      locked: true,
      items: [
        {
          id: "panel",
          name: "Main panel",
          type: "solid",
          timing: {from: 0, durationInFrames: 300},
          transform: {x: 104, y: 92, width: 1712, height: 896, rotation: 0, opacity: 1, scale: 1},
          color: "#121A2E",
          radius: 40,
        },
      ],
    },
    {
      id: "content",
      name: "Content",
      visible: true,
      locked: false,
      items: [
        {
          id: "eyebrow",
          name: "Eyebrow",
          type: "text",
          timing: {from: 12, durationInFrames: 220},
          transform: {x: 170, y: 170, width: 620, height: 70, rotation: 0, opacity: 1, scale: 1},
          text: "VMT • ERP EXPLAINER",
          style: {
            color: "#55E6C1",
            fontFamily: "Arial",
            fontSize: 30,
            fontWeight: 700,
            textAlign: "left",
            lineHeight: 1.1,
          },
        },
        {
          id: "headline",
          name: "Headline",
          type: "text",
          timing: {from: 18, durationInFrames: 220},
          transform: {x: 170, y: 250, width: 780, height: 260, rotation: 0, opacity: 1, scale: 1},
          text: "Explain any ERP workflow visually.",
          style: {
            color: "#FFFFFF",
            fontFamily: "Arial",
            fontSize: 86,
            fontWeight: 700,
            textAlign: "left",
            lineHeight: 1.02,
          },
        },
        {
          id: "body",
          name: "Body copy",
          type: "text",
          timing: {from: 28, durationInFrames: 210},
          transform: {x: 174, y: 570, width: 700, height: 180, rotation: 0, opacity: 1, scale: 1},
          text: "Build once, then swap the brand, screenshots, text and timing for YAW, Khita, Program of Action, AB4IR or any future platform.",
          style: {
            color: "#C7D1E5",
            fontFamily: "Arial",
            fontSize: 34,
            fontWeight: 400,
            textAlign: "left",
            lineHeight: 1.35,
          },
        },
        {
          id: "ui-card",
          name: "ERP UI card",
          type: "ui-card",
          timing: {from: 36, durationInFrames: 210},
          transform: {x: 1040, y: 220, width: 610, height: 500, rotation: -2, opacity: 1, scale: 1},
          title: "Project Dashboard",
          body: "Projects → Beneficiaries → Activities → Evidence → Reporting",
          accent: "#55E6C1",
          background: "#FFFFFF",
          foreground: "#111827",
        },
      ],
    },
  ],
};
